tap "homebrew/dupes"
tap "homebrew/core"
tap "homebrew/php"
tap "homebrew/versions"
tap "homebrew/bundle"
tap "homebrew/services"
tap "drone/drone"
tap "caskroom/cask"
brew "bash"
brew "coreutils"
brew "gnu-sed", args: ["with-default-names"]
brew "gnupg"
brew "jq"
brew "neovim"
brew "nvm"
brew "python"
brew "python@2"
brew "socat"
brew "tmux"
brew "tree"
brew "vim", args: ["with-python@2"]
cask "xquartz"
